config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'

  devise_for :users

  get 'home', to: 'home#show', as: 'home'

  resources :afformations, except: [:show]
  resources :sent_afformations, only: [:index, :edit, :update]

  namespace :api do
  	namespace :v1 do
      post 'user_token' => 'user_token#create'

  		resources :afformations, except: [:show]
  		resources :sent_afformations, only: [:index, :edit, :update]

      get 'home', to: 'home#first_time_or_logged_out', as: 'first_time_or_logged_out'
  	end
  end

end

app/models/sent_afformation.rb
class SentAfformation < ApplicationRecord
	belongs_to :user
	belongs_to :afformation

	scope :unanswered_first, -> { order(user_response_to_afformation: :desc) }

	delegate :afformation_text, to: :afformation

	validates :user_response_to_afformation, presence: :true, on: :update

end

app/controllers/sent_afformations_controller.rb
class SentAfformationsController < ApplicationController
	before_action :set_sent_afformation, only: [:edit, :update]
	before_action :check_if_user_permitted_to_change_afformation, only: [:edit, :update]

	def index
	    @meta_title = meta_title 'Daily Afformations - View Afformations that were sent out daily, along with answers'
		@meta_description = 'List of afformations that were sent out daily to users, along with any answers / journaled responses submitted to each daily afformation.'

		@sent_afformations = SentAfformation.where(user_id: current_user.id).unanswered_first
	end

	def edit
	end

	def update
	    respond_to do |format|
	      if @sent_afformation.update(sent_afformation_params)
	        format.html { redirect_to sent_afformations_url, notice: 'Afformation was succesfully updated with your response.' }
	        format.json { render :index, status: :ok, location: @sent_afformations }
	      else
	        format.html { render :edit }
	        format.json { render json: @sent_afformation.errors, status: :unprocessable_entity }
	      end
	    end				
	end

	private

	def sent_afformation_params
		params.require(:sent_afformation).permit(:user_response_to_afformation)
	end

	def set_sent_afformation
		@sent_afformation = SentAfformation.find(params[:id])
	end

    def check_if_user_permitted_to_change_afformation
      unless @sent_afformation.user_id == current_user.id
        handle_unauthorized_users
      end
    end

    def handle_unauthorized_users
      respond_to do |format|
        format.html { redirect_to sent_afformations_url, notice: 'You are not authorized to perform this action.' }
        format.json { render json: {}, status: :unauthorized }
      end   
    end

end

app/views/sent_afformations/edit.html.erb
<h2><%= @sent_afformation.afformation_text %></h2>
<%= form_for(@sent_afformation) do |f| %>
  <% if @sent_afformation.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@sent_afformation.errors.count, "error") %> prohibited this sent_afformation from being saved:</h4>

      <ul>
      <% @sent_afformation.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Write out an official response to remind yourself:" %><br>
    <%= f.text_area :user_response_to_afformation, class: "form-control" %>
  </div>
  </br>
  <div class="actions">
    <%= f.submit "Add Response", class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/sent_afformations/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<h2 class="text-center">Received Afformations:</h2>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Afformation:</th>
      <th scope="col">Your Response:</th>
      <th scope="col" class="text-center">Respond</th>
    </tr>
  </thead>

  <tbody>
    <% @sent_afformations.each do |sent_afformation| %>
      <tr>
        <td><%= sent_afformation.afformation_text %></td>
        <td><%= sent_afformation.user_response_to_afformation %></td>
        <td><%= link_to edit_sent_afformation_path(sent_afformation) do %>
          <div class="text-center">
            <!-- <span class="fa fa-mail-reply"></span> -->
             <span class="fa fa-pencil-square-o fa-lg btn-light"></span>
          </div>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>