config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'

  devise_for :users

  get 'home', to: 'home#show', as: 'home'

  resources :afformations, except: [:show]
  resources :sent_afformations, only: [:index, :edit, :update]

  namespace :api do
  	namespace :v1 do
      post 'user_token' => 'user_token#create'

  		resources :afformations, except: [:show]
  		resources :sent_afformations, only: [:index, :edit, :update]

      get 'home', to: 'home#first_time_or_logged_out', as: 'first_time_or_logged_out'
  	end
  end

end

app/models/afformation.rb
class Afformation < ApplicationRecord	
	include AfformationEnumMappings
	enum afformation_focus_area: Afformation.afformation_enum_mappings

	has_many :users, through: :sent_afformations
	# applies only to user-submitted afformations
	belongs_to :user, required: false

	validates_presence_of :afformation_text

end

app/controllers/afformations_controller.rb
class AfformationsController < ApplicationController
  before_action :set_afformation, only: [:edit, :update, :destroy]
  before_action :check_if_user_permitted_to_change_afformation, only: [:destroy, :update]
  
  # GET /afformations
  # GET /afformations.json
  def index
    @meta_title = meta_title 'My Personally Crafted Afformations'
    @meta_description = "View a list of all the personal afformations you've created, which will help you spur change within your life"

    if current_user.admin?
      @afformations = Afformation.where(user_id: nil)
    else
      @afformations = current_user.afformations
    end
  end

  # GET /afformations/new
  def new
    @afformation = Afformation.new
  end

  # GET /afformations/1/edit
  def edit
  end

  # POST /afformations
  # POST /afformations.json
  def create
    @meta_title = meta_title 'Daily Afformations - Create your own personal afformations'

    @afformation = Afformation.new(afformation_params)
    @afformation.user_id = current_user.id if !current_user.admin?

    respond_to do |format|
      if @afformation.save
        format.html { redirect_to afformations_url, notice: 'Afformation was successfully created.' }
        format.json { render :index, status: :created, location: @afformation }
      else
        format.html { render :new }
        format.json { render json: @afformation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /afformations/1
  # PATCH/PUT /afformations/1.json
  def update
    respond_to do |format|
      if @afformation.update(afformation_params)
        format.html { redirect_to afformations_url, notice: 'Afformation was successfully updated.' }
        format.json { render :index, status: :ok, location: @afformations }
      else
        format.html { render :edit }
        format.json { render json: @afformation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /afformations/1
  # DELETE /afformations/1.json
  def destroy
    @afformation.destroy
    respond_to do |format|
      format.html { redirect_to afformations_url, notice: 'Afformation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_afformation
      @afformation = Afformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def afformation_params
      params.require(:afformation).permit(:afformation_text, :afformation_focus_area)
    end

    def check_if_user_permitted_to_change_afformation
      unless (@afformation.user_id.nil? && current_user.admin?) || (@afformation.user_id == current_user.id)
        handle_unauthorized_users
      end
    end

    def handle_unauthorized_users
      respond_to do |format|
        format.html { redirect_to afformations_url, notice: 'You are not authorized to perform this action.' }
        format.json { render json: {}, status: :unauthorized }
      end   
    end   

end

app/controllers/api/v1/afformations_controller.rb
module Api::V1  
  class AfformationsController < ApiController
    respond_to :json
    before_action :set_afformation, only: [:edit, :update, :destroy]
    before_action :check_if_user_permitted_to_change_afformation, only: [:destroy, :update]
    
    # GET /afformations
    # GET /afformations.json
    def index
      if current_user.admin?
        @afformations = Afformation.where(user_id: nil)
      else
        @afformations = current_user.afformations
      end

      render json: { afformations: @afformations, status: :ok }
    end

    # GET /afformations/new
    def new
      @afformation = Afformation.new
      render json: { afformation: @afformation, status: :ok }
    end

    # GET /afformations/1/edit
    def edit
    end

    # POST /afformations
    # POST /afformations.json
    def create
      @afformation = Afformation.new(afformation_params)
      @afformation.user_id = current_user.id if !current_user.admin?

      if @afformation.save
        render json: { afformation: @afformation, message: "Afformation successfully created", status: :created }
      else
        render json: { errors: @afformation.errors, status: :unprocessable_entity }
      end
    end

    # PATCH/PUT /afformations/1
    # PATCH/PUT /afformations/1.json
    def update
      if @afformation.update(afformation_params)
        render json: { afformation: @afformation, message: "Afformation successfully updated", status: :ok }
      else
        render json: { errors: @afformation.errors, message: "Afformation not updated", status: :unprocessable_entity }
      end
    end

    # DELETE /afformations/1
    # DELETE /afformations/1.json
    def destroy
      @afformation.destroy

      render json: { message: "Afformation successfully deleted", status: :ok }
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_afformation
        @afformation = Afformation.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def afformation_params
        params.require(:afformation).permit(:afformation_text, :afformation_focus_area)
      end

      def check_if_user_permitted_to_change_afformation
        unless (@afformation.user_id.nil? && current_user.admin?) || (@afformation.user_id == current_user.id)
          handle_unauthorized_users
        end
      end

      def handle_unauthorized_users
        render json: { message: "Unauthorized user", status: :unauthorized }
      end   

  end
end

app/helpers/afformations_helper.rb
module AfformationsHelper
end

app/views/afformations/_form.html.erb
<%= form_for(@afformation) do |f| %>
  <% if @afformation.errors.any? %>
    <div id="error_explanation">
      <h4 class="text-danger"><%= pluralize(@afformation.errors.count, "error") %> prohibited this afformation from being saved:</h4>

      <ul>
      <% @afformation.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :afformation_text %>:<br>
    <%= f.text_field :afformation_text, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :afformation_focus_area %>:<br>
    <%= f.select :afformation_focus_area, Afformation.afformation_focus_areas.keys, class: "form-control custom-select" %>
  </div>

  <% action = params[:action].capitalize %>
  <div class="actions">
    <%= f.submit "#{action == "Edit" ? action : "Save"} Afformation", class: "btn btn-success btn-sm" %>
    <!-- btn btn-outline-success -->
  </div>
<% end %>

app/views/afformations/edit.html.erb
<h3>Edit Afformation:</h3>

<%= render 'form' %>

app/views/afformations/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<% if current_user.admin? %>
  <h2 class="text-center">All Afformations:</h2>
<% else %> 
  <h2 class="text-center">Your Personal Afformations</h2>
<% end %>

</br>
<%= link_to new_afformation_path, class: "btn btn-outline-success btn-sm centered-btn" do %>
  <span class="fa fa-plus-square-o fa-lg"> New Afformation</span>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Focus:</th>
      <th scope="col">Afformation:</th>
      <th scope="col" class="text-center">Edit</th>
      <th scope="col" class="text-center">Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @afformations.each do |afformation| %>
      <tr>
        <td><%= afformation.afformation_focus_area.capitalize %></td>
        <td><%= afformation.afformation_text %></td>
        <td><%= link_to edit_afformation_path(afformation) do %>
            <div class="text-center">
              <span class="fa fa-pencil fa-lg btn-light"></span>
            </div>
            <% end %>
        </td>
        <td><%= link_to afformation, method: :delete, data: { confirm: 'Are you sure you want to delete your afformation?' } do %>
            <div class="text-center">
              <span class="fa fa-trash-o fa-lg btn-light"></span>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/afformations/new.html.erb
<h2>Your Personal Afformation:</h2>

<%= render 'form' %>