config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'

  devise_for :users

  get 'home', to: 'home#show', as: 'home'

  resources :afformations, except: [:show]
  resources :sent_afformations, only: [:index, :edit, :update]

  namespace :api do
  	namespace :v1 do
      post 'user_token' => 'user_token#create'

  		resources :afformations, except: [:show]
  		resources :sent_afformations, only: [:index, :edit, :update]

      get 'home', to: 'home#first_time_or_logged_out', as: 'first_time_or_logged_out'
  	end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @meta_title ? @meta_title : ApplicationController::BRAND_NAME %></title>
	    <meta name="description" content="<%= @meta_description %>">

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	</head>

	<body>
		<nav class="navbar navbar-expand-md navbar-light bg-faded">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<span class="navbar-brand">Afformational Change</span>
			<%#= link_to "Afformational Change", home_index_path, class: "navbar-brand" %> <!-- post-home-page creation -->
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<% if user_signed_in? %>
						<li class="nav-item">
							<%= link_to sent_afformations_path do %>
								<i class="fa fa-envelope-o fa-lg nav-link"> Answer Afformations</i>
							<% end %>
						</li>
						<li class="nav-item">
							<%= link_to afformations_path do %>
								<i class="fa fa-plus-square-o fa-lg nav-link"> Create Afformations</i>
							<% end %>
						</li>
						<li class="nav-item">
							<%= link_to home_path do %>
								<i class="fa fa-user fa-lg nav-link"> Profile </i>
							<% end %>
						</li>
						<li class="nav-item">
							<%= link_to destroy_user_session_path, method: :delete do %>
								<i class="fa fa-sign-out fa-lg nav-link"></i>
							<% end %>
						</li>
					<% else %>
						<li class="nav-item">
							<%= link_to home_path do %>
								<i class="fa fa-user fa-lg nav-link"> Why am I excited to sign up? </i>
							<% end %>
						</li>					
						<li class="nav-item">
							<%= link_to new_user_session_path do %>
								<i class="fa fa-sign-in fa-lg nav-link"></i>
							<% end %>
						</li>			
					<% end %>    
				</ul>
			</div>
		</nav>

		<div class="container bg-light" id="site-content-container">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			<% end %>

			<%= yield %>
		</div>

	</body>
</html>